%YAML:1.0

#inputs
imu: 1         
imu_topic: "/mavros/imu/data_raw"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"

is_compressed_images: 0

imu_freq: 400
image_freq: 15
frame_step: 3

#Camera configuration
camera_configuration: 0  #STEREO_PINHOLE = 0, STEREO_FISHEYE = 1, PINHOLE_DEPTH = 2, FOURCORNER_FISHEYE = 3
num_of_cam: 2
cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 480
image_height: 270

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.003648736435669542, -0.03392277110632558, 0.9994177966810932, 0.07615430795301638,
      -0.9998094302405535, 0.01904318629621382, 0.004296540206674448, 0.007195970058629293,
      -0.01917784983992976, -0.9992430148147925, -0.03384682288430585, 0.03643188469105622,
      0, 0, 0, 1]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.005854859966095693, -0.03306950675978143, 0.9994359050671746, 0.072988178745315,
      -0.9997990445016249, 0.01896892540201978, 0.006484634355982825, -0.04056517778767008,
      -0.01917266878698947, -0.9992730295528633, -0.03295180085863358, 0.03547334787472232,
      0, 0, 0, 1]


#estimation
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.001                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
estimation_mode: 2 #0:single; 1:solve all; 2: distributed; 3:server
double_counting_common_feature: 0
min_measurements_per_keyframe: 20

#optimization parameters
max_solver_time: 0.04 # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
consensus_max_steps: 1
timout_wait_sync: 100
rho_landmark: 1.0
rho_frame_T: 100
rho_frame_theta: 100
relaxation_alpha: 0.
consensus_sync_for_averaging: 0
consensus_sync_to_start: 0 #Is sync on start of the solving..
consensus_trigger_time_err_us: 100
ceres_num_threads: 4

#depth fusing
depth_far_thres: 3.0 # The max depth in frontend
depth_near_thres: 0.3 
fuse_dep: 0 #if fuse depth measurement
max_depth_to_fuse: 5.0
min_depth_to_fuse: 0.3

#Multi-drone
track_remote_netvlad_thres: 0.5

#Initialization
init_method: 0 #0 IMU, 1 PnP
depth_estimate_baseline: 0.045

#sliding window
max_sld_win_size: 11
landmark_estimate_tracks: 3 #when use depth or stereo, 3 is OK.
min_solve_frames: 8

#solver
multiple_thread: 1

#outlier rejection
thres_outlier : 50.0
perform_outlier_rejection_num: 50
tri_max_err: 0.03

#Marginalization
enable_marginalization: 1
margin_sparse_solver: 0
always_fixed_first_pose: 0
remove_base_when_margin_remote: 2
#  When set to 2, will use the all relevant measurements of the removing frames to compute the prior,
# and the baseFrame (where!=removeID) will not be removed. This may lead to double counting of this baseFrame measurement: but it's stable.
#  When set to 1, will remove the baseframe's measurements of those measurements which is not base on current frame.
#  set to 0 those measurements (which on a landmark's baseFrame is not been removed) will be ignore.

#feature tracker parameters
max_cnt: 200            # max feature number in feature tracking
max_superpoint_cnt: 145 # max feature extraction by superpoint
max_solve_cnt: 100
show_track_id: 0
check_essential: 0
enable_lk_optical_flow: 1 #enable lk opticalflow featuretrack to enhance ego-motion estimation.
remote_min_match_num: 40
ransacReprojThreshold: 5.0
parallex_thres: 0.012
knn_match_ratio: 0.9 #This apply to superpoint feature track & loop clouse detection.
feature_min_dist: 15
enable_search_local_aera: true
search_local_max_dist: 0.06

#CNN
cnn_use_onnx: 1
enable_pca_superpoint: 1
enable_pca_netvlad: 1
superpoint_pca_dims: 64
netvlad_pca_dims: 1024
cnn_enable_tensorrt: 1
cnn_enable_tensorrt_int8: 1
netvlad_int8_calib_table_name: "mobilenetvlad_calibration.flatbuffers"
superpoint_int8_calib_table_name: "superpoint_calibration.flatbuffers"

# #Measurement parameters       The more accurate parameters you provide, the better performance
# acc_n: 0.0028         # accelerometer measurement noise standard deviation. #0.2   0.04
# gyr_n: 0.00016        # gyroscope measurement noise standard deviation.     #0.05  0.004
# acc_w: 0.00086        # accelerometer bias random work noise standard deviation.  #0.002
# gyr_w: 0.000022       # gyroscope bias random work noise standard deviation.     #4.0e-5
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.05         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.002         # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 0.0004       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805         # gravity magnitude

#Loop Closure Detection
loop_detection_netvlad_thres: 0.85
enable_homography_test: 0
loop_inlier_feature_num: 20
accept_loop_max_yaw: 10
accept_loop_max_pos: 1.0
lazy_broadcast_keyframe: 0 #If enable coarse-to-fine initialization mode. This is useful when communication is not good.
gravity_check_thres: 0.06

#PGO
pgo_mode: 1
pgo_rho_frame_T: 0.7
pgo_rho_frame_theta: 0.625
pgo_eta_k: 0.1
write_g2o: 0
g2o_output_path: "output.g2o"
write_pgo_to_file: 1
enable_gravity_prior: 0
gravity_sqrt_info: 10
pgo_solver_time: 1.0
solver_timer_freq: 1.0
enable_pcm: 1
pcm_thres: 2.8

#outputs
output_path: "/home/dji/swarm_log_latest/"
debug_print_sldwin: 0
debug_print_states: 0
enable_perf_output: 0
debug_write_margin_matrix: 0
print_network_status: 0
verbose: 0
