%YAML:1.0
---
model_type: KANNALA_BRANDT
camera_name: camera
image_width: 512
image_height: 512
projection_parameters:
   k2: 0.0034003170790442797
   k3: 0.001766278153469831
   k4: -0.00266312569781606
   k5: 0.0003299517423931039
   mu: 190.44236969414825
   mv: 190.4344384721956
   u0: 252.59949716835982
   v0: 254.91723064636983