name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-AMD64:

    runs-on: [self-hosted, linux, x64]

    steps:
    -
      name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_ACCOUNT }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: |
          hkustswarm/d2slam:${{ steps.date.outputs.today }}
          hkustswarm/d2slam:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

  build-ARM64:

    runs-on: [self-hosted, linux, arm64]

    steps:
    -
      name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_ACCOUNT }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build-base and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: docker/Dockerfile.jetson_base_35.1.0
        push: true
        tags: |
          hkustswarm/d2slam:jetson_base_35.1.0-${{ steps.date.outputs.today }}
          hkustswarm/d2slam:jetson_base_35.1.0
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
    -
      name: Build-app and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: docker/Dockerfile.jetson
        push: true
        tags: |
          hkustswarm/d2slam:jetson-${{ steps.date.outputs.today }}
          hkustswarm/d2slam:jetson
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache